#!/usr/bin/env python3
"""Build a flat HoriScope KBS submission from the accepted PDT source layout."""

from __future__ import annotations

import argparse
import re
import shutil
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MANUSCRIPT = ROOT / "manuscript"
TARGET = ROOT / "HoriScope_KBS_submission"
PDT_SOURCE = Path(
    "/Users/river/PaperResearch/Project/R_2026_PDT/manuscript/revision/"
    "PDT_revision_v01/source_latex"
)
PDT_MAIN = PDT_SOURCE / "elsarticle-template-num.tex"

TITLE = (
    "HoriScope: Adaptive Multi-Scope Decoding for Unified Varied-Horizon "
    "Time-Series Forecasting"
)

HIGHLIGHTS = (
    "Unified varied-horizon forecasting is formalized with nested trajectory prefixes.",
    "HoriScope adaptively combines forecasts generated under multiple sharing scopes.",
    "Balanced training supports joint optimization of all forecasting scopes.",
    "One model achieves state-of-the-art accuracy across seven forecasting benchmarks.",
)

MAIN_SECTIONS = (
    "01_introduction.tex",
    "02_related_work.tex",
    "03_problem_formulation.tex",
    "04_method.tex",
    "05_experiments.tex",
    "06_discussion.tex",
    "07_conclusion.tex",
)


def extract_environment(text: str, name: str) -> str:
    """Return the body of the first named LaTeX environment."""
    match = re.search(
        rf"\\begin\{{{name}\}}(.*?)\\end\{{{name}\}}",
        text,
        re.DOTALL,
    )
    if match is None:
        raise RuntimeError(f"Missing {name} environment")
    return match.group(1).strip()


def inline_tables(text: str) -> str:
    """Replace manuscript table inputs with their complete LaTeX source."""
    pattern = re.compile(r"\\input\{tables/([^}]+)\}")

    def replacement(match: re.Match[str]) -> str:
        filename = match.group(1)
        if not filename.endswith(".tex"):
            filename += ".tex"
        table_path = MANUSCRIPT / "tables" / filename
        if not table_path.exists():
            raise FileNotFoundError(table_path)
        return table_path.read_text(encoding="utf-8").strip()

    return pattern.sub(replacement, text)


def prepare_body(text: str) -> str:
    """Inline tables and convert all figure references to flat paths."""
    text = re.sub(
        r"\A% Generated by manuscript/build_manuscript\.py\.\s*",
        "",
        text,
    )
    text = inline_tables(text)
    text = text.replace("{figures/", "{")
    return text.strip()


def split_pdt_scaffold(reference: str) -> tuple[str, str, str, str, str]:
    """Extract immutable PDT layout fragments around replaceable metadata."""
    old_title = (
        r"\title{PDT: Predictive Domain Transform for Multivariate Time Series "
        r"Forecasting}"
    )
    prefix, remainder = reference.split(old_title, maxsplit=1)
    author_block, remainder = remainder.split(r"\begin{abstract}", maxsplit=1)
    _, remainder = remainder.split(r"\end{abstract}", maxsplit=1)
    between_abstract_and_highlights, remainder = remainder.split(
        r"\begin{highlights}", maxsplit=1
    )
    _, remainder = remainder.split(r"\end{highlights}", maxsplit=1)
    between_highlights_and_keywords, remainder = remainder.split(
        r"\begin{keyword}", maxsplit=1
    )
    _, remainder = remainder.split(r"\end{keyword}", maxsplit=1)
    post_frontmatter, _ = remainder.split(r"\section{Introduction}", maxsplit=1)
    return (
        prefix,
        author_block,
        between_abstract_and_highlights,
        between_highlights_and_keywords,
        post_frontmatter,
    )


def bibliography_tail(reference: str) -> str:
    """Reuse the PDT bibliography/end-document block verbatim."""
    marker = "%% For citations use:"
    if marker not in reference:
        raise RuntimeError("PDT bibliography marker not found")
    return reference[reference.rindex(marker):].strip()


def build_main_tex() -> str:
    """Assemble one submission TeX file under the PDT layout contract."""
    reference = PDT_MAIN.read_text(encoding="utf-8")
    current_main = (MANUSCRIPT / "main.tex").read_text(encoding="utf-8")
    abstract = extract_environment(current_main, "abstract")
    (
        prefix,
        author_block,
        between_abstract_and_highlights,
        between_highlights_and_keywords,
        post_frontmatter,
    ) = split_pdt_scaffold(reference)

    main_body = "\n\n".join(
        prepare_body((MANUSCRIPT / "sections" / name).read_text(encoding="utf-8"))
        for name in MAIN_SECTIONS
    )
    appendix_body = prepare_body(
        (MANUSCRIPT / "sections/appendices.tex").read_text(encoding="utf-8")
    )

    highlights = "\n".join(f"\\item {item}" for item in HIGHLIGHTS)
    keywords = """Time series forecasting,
Unified varied-horizon forecasting,
Cross-horizon prefix consistency,
Multi-scope forecasting,
Adaptive forecast generation."""

    declarations = r"""
\section*{CRediT authorship contribution statement}
\indent \textbf{Chenhao Ying:} Writing -- original draft, Writing - review \& editing, Visualization, Validation, Supervision, Software, Resources, Project administration, Methodology, Investigation. \textbf{Jiangang Lu:} Writing - review \& editing, Conceptualization.

\section*{Declaration of Competing Interest}
\indent The authors declare that they have no known competing financial interests or personal relationships that could have appeared to influence the work reported in this paper.

\section*{Data availability}
Data will be made available on request.

\section*{Acknowledgments}
This work was supported in part by the National Natural Science Foundation of China under Grant 62293504, 62293500, and in part by Zhejiang Province Science and Technology Plan Project under Grant 2025C01091.
""".strip()

    assembled = f"""{prefix}\\title{{{TITLE}}}{author_block}\\begin{{abstract}}
{abstract}
\\end{{abstract}}{between_abstract_and_highlights}\\begin{{highlights}}
{highlights}
\\end{{highlights}}{between_highlights_and_keywords}\\begin{{keyword}}
{keywords}
\\end{{keyword}}{post_frontmatter}
%% BEGIN INLINED HORISCOPE MAIN TEXT
{main_body}
%% END INLINED HORISCOPE MAIN TEXT

{declarations}

\\appendix
\\renewcommand*{{\\theHtable}}{{appendix.\\Alph{{section}}.\\arabic{{table}}}}
\\renewcommand*{{\\theHfigure}}{{appendix.\\Alph{{section}}.\\arabic{{figure}}}}

%% BEGIN INLINED HORISCOPE APPENDICES
{appendix_body}
%% END INLINED HORISCOPE APPENDICES

{bibliography_tail(reference)}
"""
    return assembled.rstrip() + "\n"


def parse_args() -> argparse.Namespace:
    """Parse command-line options."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Refresh the existing flat submission in place.",
    )
    return parser.parse_args()


def main() -> None:
    """Create the clean flat directory and all submission assets."""
    args = parse_args()
    if TARGET.exists():
        if not args.overwrite:
            raise FileExistsError(
                f"Refusing to overwrite existing submission directory: {TARGET}"
            )
    else:
        TARGET.mkdir()

    for filename in (".latexmkrc", "elsarticle-num.bst", "math_utils.tex"):
        shutil.copy2(PDT_SOURCE / filename, TARGET / filename)
    shutil.copy2(MANUSCRIPT / "ref.bib", TARGET / "ref.bib")
    for figure_path in sorted((MANUSCRIPT / "figures").iterdir()):
        if figure_path.is_file():
            shutil.copy2(figure_path, TARGET / figure_path.name)

    (TARGET / "elsarticle-template-num.tex").write_text(
        build_main_tex(),
        encoding="utf-8",
        newline="\n",
    )
    action = "Refreshed" if args.overwrite else "Created"
    print(f"{action} flat KBS submission at {TARGET}")


if __name__ == "__main__":
    main()
